#!/usr/bin/env python3
"""Generate the SRAG data dictionary from the two authoritative sources.

Neither source alone is enough:

  * the Ministry's PDF (``dicionario-de-dados-2019-a-2025.pdf``) defines the
    fields and their coded values, but it documents a *form*, not the file
    that is actually published — it names fields the data does not carry, and
    misses fields the data does;
  * the parquet files are the ground truth for which columns exist, but carry
    no descriptions.

So the dictionary is generated by anchoring the PDF's text on the real column
names, and every field is annotated with its measured fill rate per year. The
fill rates come from parquet column statistics (null counts in the file
metadata), not from reading the data, so this is cheap and exact.

Where the two disagree, the parquet wins and the disagreement is reported.

Usage:  python3 tools/build_srag_dictionary.py [data_dir] [output.md]
        (defaults: ~/Documents/srag-data, modules/00-dataset/DICTIONARY.md)
"""

from __future__ import annotations

import pathlib
import re
import sys

import pyarrow.parquet as pq
from pypdf import PdfReader

PDF = "dicionario-de-dados-2019-a-2025.pdf"
FOOTER = re.compile(
    r"SIVEP Gripe- Sistema de Informação da Vigilância Epidemiológica da Gripe\.\s*Página \d+"
)

# Field blocks, in the order the notification form walks through a case.
# Every one of the 194 published columns belongs to exactly one block; the
# script fails loudly if that stops being true.
BLOCKS: list[tuple[str, list[str]]] = [
    (
        "Identificação e notificação",
        [
            "NU_NOTIFIC",
            "DT_NOTIFIC",
            "SEM_NOT",
            "DT_SIN_PRI",
            "SEM_PRI",
            "SG_UF_NOT",
            "ID_REGIONA",
            "CO_REGIONA",
            "ID_MUNICIP",
            "CO_MUN_NOT",
            "ID_UNIDADE",
            "CO_UNI_NOT",
            "DT_DIGITA",
            "TEM_CPF",
            "ESTRANG",
            "SURTO_SG",
            "NOSOCOMIAL",
            "AVE_SUINO",
            "OUT_ANIM",
        ],
    ),
    (
        "Demografia e residência",
        [
            "CS_SEXO",
            "DT_NASC",
            "NU_IDADE_N",
            "TP_IDADE",
            "COD_IDADE",
            "CS_GESTANT",
            "CS_RACA",
            "CS_ETINIA",
            "CS_ESCOL_N",
            "CS_ZONA",
            "POV_CT",
            "TP_POV_CT",
            "ID_PAIS",
            "CO_PAIS",
            "SG_UF",
            "ID_RG_RESI",
            "CO_RG_RESI",
            "ID_MN_RESI",
            "CO_MUN_RES",
            "PAC_COCBO",
            "PAC_DSCBO",
        ],
    ),
    (
        "Sinais e sintomas",
        [
            "FEBRE",
            "TOSSE",
            "GARGANTA",
            "DISPNEIA",
            "DESC_RESP",
            "SATURACAO",
            "DIARREIA",
            "VOMITO",
            "DOR_ABD",
            "FADIGA",
            "PERD_OLFT",
            "PERD_PALA",
            "OUTRO_SIN",
            "OUTRO_DES",
        ],
    ),
    (
        "Comorbidades e fatores de risco",
        [
            "FATOR_RISC",
            "PUERPERA",
            "CARDIOPATI",
            "HEMATOLOGI",
            "SIND_DOWN",
            "HEPATICA",
            "ASMA",
            "DIABETES",
            "NEUROLOGIC",
            "PNEUMOPATI",
            "IMUNODEPRE",
            "RENAL",
            "OBESIDADE",
            "OBES_IMC",
            "OUT_MORBI",
            "MORB_DESC",
            "TABAG",
        ],
    ),
    (
        "Vacinação",
        [
            "VACINA",
            "DT_UT_DOSE",
            "MAE_VAC",
            "DT_VAC_MAE",
            "M_AMAMENTA",
            "DT_DOSEUNI",
            "DT_1_DOSE",
            "DT_2_DOSE",
            "VACINA_COV",
            "DOSE_1_COV",
            "DOSE_2_COV",
            "DOSE_REF",
            "DOSE_2REF",
            "DOSE_ADIC",
            "DOS_RE_BI",
            "FAB_COV_1",
            "FAB_COV_2",
            "FAB_COVRF",
            "FAB_COVRF2",
            "FAB_ADIC",
            "FAB_RE_BI",
            "LOTE_1_COV",
            "LOTE_2_COV",
            "LOTE_REF",
            "LOTE_REF2",
            "LOTE_ADIC",
            "LOT_RE_BI",
            "FNT_IN_COV",
        ],
    ),
    (
        "Internação, UTI e suporte ventilatório",
        [
            "HOSPITAL",
            "DT_INTERNA",
            "SG_UF_INTE",
            "ID_RG_INTE",
            "CO_RG_INTE",
            "ID_MN_INTE",
            "CO_MU_INTE",
            "NM_UN_INTE",
            "UTI",
            "DT_ENTUTI",
            "DT_SAIDUTI",
            "SUPORT_VEN",
        ],
    ),
    (
        "Tratamento",
        [
            "ANTIVIRAL",
            "TP_ANTIVIR",
            "OUT_ANTIV",
            "DT_ANTIVIR",
            "TRAT_COV",
            "TIPO_TRAT",
            "DT_TRT_COV",
            "OUT_TRAT",
        ],
    ),
    (
        "Imagem",
        ["RAIOX_RES", "RAIOX_OUT", "DT_RAIOX", "TOMO_RES", "TOMO_OUT", "DT_TOMO"],
    ),
    (
        "Laboratório — RT-PCR",
        [
            "AMOSTRA",
            "DT_COLETA",
            "TP_AMOSTRA",
            "OUT_AMOST",
            "PCR_RESUL",
            "DT_PCR",
            "POS_PCRFLU",
            "TP_FLU_PCR",
            "PCR_FLUASU",
            "FLUASU_OUT",
            "PCR_FLUBLI",
            "FLUBLI_OUT",
            "POS_PCROUT",
            "PCR_VSR",
            "PCR_PARA1",
            "PCR_PARA2",
            "PCR_PARA3",
            "PCR_PARA4",
            "PCR_ADENO",
            "PCR_METAP",
            "PCR_BOCA",
            "PCR_RINO",
            "PCR_OUTRO",
            "DS_PCR_OUT",
            "PCR_SARS2",
        ],
    ),
    (
        "Laboratório — antigênico e sorologia",
        [
            "TP_TES_AN",
            "DT_RES_AN",
            "RES_AN",
            "POS_AN_FLU",
            "TP_FLU_AN",
            "POS_AN_OUT",
            "AN_SARS2",
            "AN_VSR",
            "AN_PARA1",
            "AN_PARA2",
            "AN_PARA3",
            "AN_ADENO",
            "AN_OUTRO",
            "DS_AN_OUT",
            "TP_AM_SOR",
            "SOR_OUT",
            "DT_CO_SOR",
            "TP_SOR",
            "OUT_SOR",
            "DT_RES",
            "RES_IGG",
            "RES_IGM",
            "RES_IGA",
        ],
    ),
    (
        "Vigilância genômica e reinfecção",
        [
            "CO_DETEC",
            "VG_OMS",
            "VG_OMSOUT",
            "VG_LIN",
            "VG_MET",
            "VG_METOUT",
            "VG_DTRES",
            "VG_ENC",
            "VG_REINF",
            "VG_CODEST",
            "REINF",
        ],
    ),
    (
        "Histórico de viagem",
        [
            "HISTO_VGM",
            "PAIS_VGM",
            "CO_PS_VGM",
            "LO_PS_VGM",
            "DT_VGM",
            "DT_RT_VGM",
        ],
    ),
    (
        "Encerramento e desfecho",
        [
            "CLASSI_FIN",
            "CLASSI_OUT",
            "CRITERIO",
            "EVOLUCAO",
            "DT_EVOLUCA",
            "DT_ENCERRA",
        ],
    ),
]

# Fields that are a *consequence* of the outcome, or encode it. Using any of
# these to predict EVOLUCAO is leakage, not prediction.
LEAKAGE = {
    "DT_EVOLUCA": "outcome date — only exists once the outcome has happened",
    "DT_ENCERRA": "case closure date",
    "UTI": "ICU admission follows from severity and is contemporaneous with the outcome",
    "DT_ENTUTI": "same, and posterior to admission",
    "DT_SAIDUTI": "same",
    "SUPORT_VEN": "ventilatory support follows from severity",
    "CLASSI_FIN": "final case classification, assigned at closure",
    "CRITERIO": "closure criterion",
    "VG_ENC": "genomic-surveillance closure",
}


# The PDF spells a few fields differently from the published data. Anchoring on
# the variant too keeps their rows from being swallowed by the next field.
ALIASES = {"CO_DETEC": "CO-DETEC", "FAB_COV_1": "FAB_COV1", "FAB_COV_2": "FAB_COV2"}


def parse_pdf(pdf_path: pathlib.Path, columns: list[str]) -> dict[str, str]:
    """Slice the PDF text into rows, keyed on the DBF name that ends each row.

    Three things make the naive slice wrong, and each is handled here:

    * The PDF documents the whole notification form, including the fields the
      public release strips (NM_PACIENT, NU_CPF, NU_CNS, NM_MAE_PAC, address).
      Anchoring only on published columns lets a stripped field's row bleed into
      its neighbour's label, so every DBF-shaped token anchors, and only the
      published ones are emitted.
    * A short field name also appears inside its own label — "O paciente foi
      internado em UTI? Campo Essencial UTI 54-Data da entrada na UTI". The
      occurrence that actually ends a row is the one followed by the next row's
      field number; anything else is prose.
    * The front matter (cover, the four field-class definitions, the table
      header) would otherwise become the first field's label.
    """
    text = "\n".join(
        (page.extract_text() or "") for page in PdfReader(str(pdf_path)).pages
    )
    text = FOOTER.sub(" ", text)

    header = re.search(r"Nome\s+do\s+campo\s+Tipo\s+Categoria[\s\S]{0,80}?DBF", text)
    if header:
        text = text[header.end() :]

    anchors: dict[str, str | None] = {}
    for col in columns:
        for spelling in {col, ALIASES.get(col, col)}:
            anchors[spelling] = col
    for m in re.finditer(r"(?<![A-Z0-9_-])([A-Z][A-Z0-9_]{4,11})(?![A-Z0-9_])", text):
        anchors.setdefault(m.group(1), None)  # documented, not published

    next_row = re.compile(r"\s*\d{1,3}\s*[-\u2013]")
    hits: list[tuple[int, int, str | None]] = []
    for spelling, col in anchors.items():
        pattern = r"(?<![A-Z0-9_-])" + re.escape(spelling) + r"(?![A-Z0-9_])"
        found = list(re.finditer(pattern, text))
        if col is not None:
            row_end = [m for m in found if next_row.match(text, m.end())]
            if row_end:
                found = row_end
        hits += [(m.start(), m.end(), col) for m in found]
    hits.sort()

    out: dict[str, str] = {}
    prev_end = 0
    for start, end, col in hits:
        if col is None or col in out:
            prev_end = max(prev_end, end)
            continue
        out[col] = re.sub(r"\s+", " ", text[prev_end:start]).strip()
        prev_end = end
    return out


def fill_rates(
    files: list[pathlib.Path],
) -> tuple[dict[str, dict[str, float]], dict[str, int]]:
    """Non-null share per column per year, straight from parquet column statistics."""
    rates: dict[str, dict[str, float]] = {}
    totals: dict[str, int] = {}
    for f in files:
        year = "20" + f.name[6:8]
        md = pq.ParquetFile(f).metadata
        totals[year] = md.num_rows
        names = list(pq.ParquetFile(f).schema_arrow.names)
        nulls = dict.fromkeys(names, 0)
        for rg in range(md.num_row_groups):
            for ci, name in enumerate(names):
                stats = md.row_group(rg).column(ci).statistics
                nulls[name] += stats.null_count if stats is not None else 0
        for name in names:
            rates.setdefault(name, {})[year] = 100 * (1 - nulls[name] / md.num_rows)
    return rates, totals


def split_definition(raw: str) -> tuple[str, str, str, str]:
    """Split one parsed table row into (label, type, coded values, obligation class).

    A row in the PDF flattens to:
        "35-Fatores de risco/ Doença Cardiovascular Crônica  Varchar2 (1)
         1-Sim 2-Não 9-Ignorado  Paciente possui Doença Cardiovascular Crônica?
         Campo Essencial"
    i.e. label, type, coded values, description, obligation class. The slice fed
    in here starts wherever the previous row's DBF name ended, so its head often
    carries the tail of that previous row — anchor on the last field number to
    drop it.
    """
    klass = ""
    m = re.search(r"Campo (Obrigatório|Essencial|Interno|Opcional)", raw)
    if m:
        klass = m.group(1)
        raw = raw[: m.start()].strip()

    tipo = ""
    m = re.search(
        r"(Varchar2?\s*\(\s*\d+\s*\)|Date\s*DD/MM/AAAA|Numérico\s*\(\d+[^)]*\))", raw
    )
    if m:
        tipo = re.sub(r"\s+", "", m.group(1))
        head, tail = raw[: m.start()].strip(), raw[m.end() :].strip()
    else:
        head, tail = raw.strip(), ""

    # The label is what follows the LAST field number in the head; anything
    # before it belongs to the previous row.
    starts = list(re.finditer(r"(?:^|\s)(\d{1,3})\s*[-–]\s*", head))
    label = head[starts[-1].end() :] if starts else head
    label = re.sub(r"\s+", " ", label).strip(" .;,/")

    # Coded values are the run of "N-Something" tokens at the head of the tail.
    # The trailing one has no following number to stop it, so it swallows the
    # description ("9-Ignorado Paciente possui Asma?"). Every code in a given
    # row is a short label, so truncate the last one to the longest word count
    # seen in its siblings — data-driven, rather than a guessed cutoff.
    marks = list(re.finditer(r"(\d{1,2})\s*[-–.]\s+|(\d{1,2})\s*[-–]\s*", tail))
    codes, desc = [], ""
    if marks:
        segs = []
        for i, mk in enumerate(marks):
            stop = marks[i + 1].start() if i + 1 < len(marks) else len(tail)
            segs.append((mk.group(1) or mk.group(2), tail[mk.end() : stop].strip()))
        width = max((len(t.split()) for _, t in segs[:-1]), default=2)
        out = []
        for i, (num, text) in enumerate(segs):
            words = text.split()
            if i == len(segs) - 1 and len(words) > width:
                out.append(f"{num}-{' '.join(words[:width]).strip(' .;,')}")
                desc = " ".join(words[width:])
            else:
                out.append(f"{num}-{text.strip(' .;,')}")
        codes = out
    else:
        desc = tail
    valores = "; ".join(codes[:9])
    desc = re.sub(r"\s+", " ", desc).strip(" .;,")

    # The trailing code often carries a description that merely repeats the
    # label ("9-Ignorado Evolução do caso"); drop that echo.
    if codes and label:
        norm = lambda t: re.sub(r"[^a-zà-ÿ ]", "", t.lower()).strip()
        last = codes[-1]
        for cut in range(1, len(last.split())):
            head, tailwords = " ".join(last.split()[:cut]), " ".join(last.split()[cut:])
            if norm(tailwords) == norm(label):
                codes[-1] = head.strip(" .;,")
                valores = "; ".join(codes[:9])
                break

    # Prefer the sentence-form description when the PDF gives one; it is the
    # question the form actually asks.
    if desc and len(desc) > 8 and len(label) < 4:
        label = desc
    return label, tipo, valores, klass


def main(argv: list[str]) -> int:
    root = pathlib.Path(__file__).resolve().parent.parent
    data = (
        pathlib.Path(argv[0]).expanduser()
        if argv
        else pathlib.Path.home() / "Documents/srag-data"
    )
    out_path = (
        pathlib.Path(argv[1])
        if len(argv) > 1
        else root / "modules/00-dataset/DICTIONARY.md"
    )

    files = sorted(data.glob("INFLUD*.parquet"))
    if not files:
        print(
            f"no INFLUD*.parquet under {data} — run tools/fetch_srag.sh first",
            file=sys.stderr,
        )
        return 2

    columns = list(pq.ParquetFile(files[0]).schema_arrow.names)
    defs = parse_pdf(data / PDF, columns)
    rates, totals = fill_rates(files)
    years = sorted(totals)

    classified = {c for _, cs in BLOCKS for c in cs}
    unplaced = [c for c in columns if c not in classified]
    if unplaced:
        print(f"columns not assigned to a block: {unplaced}", file=sys.stderr)
        return 2

    L: list[str] = []
    L.append("# SRAG / SIVEP-Gripe — data dictionary\n")
    L.append(
        "Generated by [`tools/build_srag_dictionary.py`](../../tools/build_srag_dictionary.py) "
        "from two sources, because neither is sufficient alone: the Ministry of Health's official "
        "dictionary (`dicionario-de-dados-2019-a-2025.pdf`, dated 2023-05-25) defines the fields "
        "and their coded values, and the published parquet files say which columns actually exist. "
        "**Where the two disagree the data wins**, and the disagreement is recorded below.\n"
    )
    L.append(
        "Field labels and coded values are kept in Portuguese: they are the official names on the "
        "notification form, and translating them would break the link to the source.\n"
    )
    L.append("Do not edit this file by hand — run the generator.\n")

    L.append("## Coverage\n")
    L.append("| Year | Records | Extraction |")
    L.append("|---|---:|---|")
    for y in years:
        L.append(f"| {y} | {totals[y]:,} | frozen bank 2025-06-26 |")
    L.append(
        f"\n**{len(columns)} columns**, identical across all {len(years)} years.\n"
    )

    L.append("## Reading this table\n")
    L.append(
        "- **Class** is the official form's: *Obrigatório* blocks the record if absent, "
        "*Essencial* is needed for the investigation but does not block, *Interno* is filled by "
        "the system itself, *Opcional* only when applicable. It explains **why** a field is "
        "missing.\n"
        "- **Year columns** give the share of records with a non-null value, measured from the "
        "parquet column statistics.\n"
        "- ⚠️ marks a field that is a *consequence* of the outcome: using it to predict "
        "`EVOLUCAO` is leakage, not prediction.\n"
    )
    L.append(
        "> **Blank is not `9-Ignorado`.** They are different things, and the distinction is this "
        "dataset's central trap. A blank is an absence of record; `9` is an explicit record of "
        "not knowing. On the comorbidities, treating blank as `2-Não` inverts the prevalence — in "
        "2021 `CARDIOPATI` is blank in 56.1% of records and, among those filled, 62.5% say *Sim*; "
        "treating blank as *Não* would report 27.5% with heart disease instead of 62.5%.\n"
    )

    hdr = "| Field | Label | Type | Coded values | Class | " + " | ".join(years) + " |"
    sep = "|---|---|---|---|---|" + "---:|" * len(years)

    for title, cols in BLOCKS:
        present = [c for c in cols if c in columns]
        if not present:
            continue
        L.append(f"\n## {title}\n")
        L.append(hdr)
        L.append(sep)
        for c in present:
            label, tipo, valores, klass = split_definition(defs.get(c, ""))
            flag = " ⚠️" if c in LEAKAGE else ""
            r = " | ".join(f"{rates[c][y]:.0f}%" for y in years)
            label = label or "_(not in the official dictionary)_"
            if len(label) > 140:
                label = label[:137].rstrip() + "…"
            if len(valores) > 140:
                valores = valores[:137].rstrip() + "…"
            L.append(f"| `{c}`{flag} | {label} | {tipo} | {valores} | {klass} | {r} |")

    L.append("\n## Where the official dictionary and the published data disagree\n")
    absent = [c for c in columns if c not in defs]
    L.append(
        f"**{len(absent)} columns exist in the parquet and are not defined in the official PDF.** "
        "The published dictionary is dated 2023-05-25 and did not follow every revision of the "
        "form:\n"
    )
    for c in absent:
        L.append(f"- `{c}`")
    L.append(
        "\nThe PDF also spells `CO-DETEC`, `FAB_COV1` and `FAB_COV2` where the data publishes "
        "`CO_DETEC`, `FAB_COV_1` and `FAB_COV_2`; the generator anchors on both spellings.\n"
    )

    L.append("## Fields that leak the outcome\n")
    L.append("| Field | Why |")
    L.append("|---|---|")
    for c, why in LEAKAGE.items():
        if c in columns:
            L.append(f"| `{c}` | {why} |")
    L.append(
        "\nNone of these should enter as a predictor of `EVOLUCAO` unless the module states "
        "explicitly that it is measuring association, not prediction.\n"
    )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    # Exactly one trailing newline: several sections end with a blank line of
    # their own, and end-of-file-fixer would otherwise rewrite what we generate.
    out_path.write_text("\n".join(L).rstrip("\n") + "\n", encoding="utf-8")
    print(f"{out_path}: {len(columns)} fields, {len(defs)} with an official definition")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
