#!/usr/bin/env python3
"""Profile every SRAG column, in every year, and commit the result.

This exists because of a specific recurring failure: measuring one year and
stating the finding as if it held for all six. That produced, among others, the
claim that the laboratory checkbox columns only ever hold '1' — true in five
years, false in 2020, where they hold '1.0'. A rule written from that claim
would have silently discarded 519,518 COVID-positive records while leaving the
row count intact.

Two design choices follow from that, and both are deliberate constraints rather
than conveniences:

  * **There is no year parameter.** `profile()` takes a directory and profiles
    whatever years it finds. A caller cannot ask for one year, so a finding
    cannot accidentally be scoped to one.
  * **Values are reported raw.** No stripping, no `.0` normalisation, no case
    folding. Normalisation is what hid the 2020 defect; a profile that
    normalises cannot show you that your normalisation is wrong.

The `formats` column is the load-bearing one: it buckets each value by shape,
so `'1'` and `'1.0'` appear as different shapes of the same logical value and a
year-to-year shape change is visible without knowing to look for it.

Usage:  python3 tools/srag_profile.py [data_dir] [out.md]
        (defaults: ~/Documents/srag-data, modules/00-dataset/PROFILE.md)
"""

from __future__ import annotations

import collections
import json
import pathlib
import re
import sys

import pyarrow.parquet as pq

BATCH = 200_000
TOP_VALUES = 8  # distinct values listed per column-year, when few enough
MAX_DISTINCT = 400  # above this a column is summarised, not enumerated

# Value shapes, in priority order. The first match wins, so put the specific
# ones first: '1.0' must not be swallowed by the decimal bucket.
SHAPES: list[tuple[str, re.Pattern[str]]] = [
    ("int", re.compile(r"^-?\d+$")),
    ("int.0", re.compile(r"^-?\d+\.0+$")),  # the 2020 defect looks like this
    ("decimal", re.compile(r"^-?\d+\.\d*[1-9]\d*$")),
    ("iso-date", re.compile(r"^\d{4}-\d{2}-\d{2}$")),
    ("iso-datetime", re.compile(r"^\d{4}-\d{2}-\d{2}[ T]\d")),
    ("dmy-date", re.compile(r"^\d{2}/\d{2}/\d{4}$")),
    ("alpha", re.compile(r"^[A-Za-zÀ-ÿ][A-Za-zÀ-ÿ\s.'-]*$")),
    ("blank-ish", re.compile(r"^\s+$")),
]


def shape_of(value: str) -> str:
    for name, pattern in SHAPES:
        if pattern.match(value):
            return name
    return "other"


def profile_file(path: pathlib.Path) -> dict:
    """One year. Streams in batches, so a single row group is not a problem."""
    pf = pq.ParquetFile(path)
    columns = list(pf.schema_arrow.names)
    n_rows = pf.metadata.num_rows

    counts: dict[str, collections.Counter] = {c: collections.Counter() for c in columns}
    shapes: dict[str, collections.Counter] = {c: collections.Counter() for c in columns}
    nulls = dict.fromkeys(columns, 0)
    overflowed: set[str] = set()

    for batch in pf.iter_batches(batch_size=BATCH):
        for c in columns:
            col = batch.column(columns.index(c))
            for value in col.to_pylist():
                if value is None:
                    nulls[c] += 1
                    continue
                shapes[c][shape_of(value)] += 1
                if c in overflowed:
                    continue
                counts[c][value] += 1
                if len(counts[c]) > MAX_DISTINCT:
                    overflowed.add(c)

    out = {}
    for c in columns:
        filled = n_rows - nulls[c]
        out[c] = {
            "n_rows": n_rows,
            "n_null": nulls[c],
            "fill": 100 * filled / n_rows if n_rows else 0.0,
            "n_distinct": None if c in overflowed else len(counts[c]),
            "top": [] if c in overflowed else counts[c].most_common(TOP_VALUES),
            "shapes": dict(shapes[c].most_common()),
        }
    return out


def profile(data_dir: pathlib.Path) -> dict[str, dict]:
    """Every INFLUD file in the directory. There is deliberately no way to ask
    for a subset — see the module docstring."""
    files = sorted(data_dir.glob("INFLUD*.parquet"))
    if not files:
        raise FileNotFoundError(f"no INFLUD*.parquet under {data_dir}")
    by_year = {}
    for f in files:
        year = "20" + re.search(r"INFLUD(\d\d)", f.name).group(1)
        print(f"  {year} …", end="", flush=True)
        by_year[year] = profile_file(f)
        print(f" {by_year[year][next(iter(by_year[year]))]['n_rows']:,} linhas")
    return by_year


def render(by_year: dict[str, dict]) -> str:
    years = sorted(by_year)
    columns = sorted({c for y in years for c in by_year[y]})

    L: list[str] = []
    L.append("# SRAG — column profile, all years\n")
    L.append(
        "Generated by [`tools/srag_profile.py`](../../tools/srag_profile.py). Every column, "
        "every year, values reported **raw** — no stripping and no `.0` normalisation, because "
        "normalising is what hides the defects this file exists to surface.\n"
    )
    L.append(
        "The generator has no year parameter. It profiles whatever years it finds, so a finding "
        "taken from here cannot accidentally be scoped to one year — which is the mistake that "
        "made this file necessary.\n"
    )
    L.append("Do not edit by hand — run the generator.\n")

    L.append("## Coverage\n")
    L.append("| Year | Records | Columns |")
    L.append("|---|---:|---:|")
    for y in years:
        any_col = next(iter(by_year[y]))
        L.append(f"| {y} | {by_year[y][any_col]['n_rows']:,} | {len(by_year[y])} |")

    L.append("\n## Value shapes that change between years\n")
    L.append(
        "A column whose values change shape across years breaks any rule written as a literal "
        "string comparison. This is the section to read before writing one.\n"
    )
    L.append("| Column | " + " | ".join(years) + " |")
    L.append("|---|" + "---|" * len(years))
    drifted = 0
    for c in columns:
        sets = []
        for y in years:
            info = by_year[y].get(c)
            sets.append(frozenset(info["shapes"]) if info else frozenset())
        non_empty = [s for s in sets if s]
        if len(set(non_empty)) <= 1:
            continue
        drifted += 1
        cells = ["/".join(sorted(s)) if s else "—" for s in sets]
        L.append(f"| `{c}` | " + " | ".join(cells) + " |")
    if not drifted:
        L.append("| _(none)_ | " + " | ".join("—" for _ in years) + " |")
    L.append(
        f"\n**{drifted} of {len(columns)} columns change value shape between years.**\n"
    )

    L.append("\n## Fill rate\n")
    L.append("| Column | " + " | ".join(years) + " |")
    L.append("|---|" + "---:|" * len(years))
    for c in columns:
        cells = []
        for y in years:
            info = by_year[y].get(c)
            cells.append(f"{info['fill']:.1f}%" if info else "—")
        L.append(f"| `{c}` | " + " | ".join(cells) + " |")

    L.append("\n## Distinct values\n")
    L.append(
        "`—` means the column exceeded the enumeration cap and is an identifier or free text. "
        "Counts and values are raw.\n"
    )
    for y in years:
        L.append(f"\n### {y}\n")
        L.append("| Column | Distinct | Values (raw, with counts) |")
        L.append("|---|---:|---|")
        for c in columns:
            info = by_year[y].get(c)
            if info is None:
                continue
            n = info["n_distinct"]
            if n is None:
                vals = "_(over cap — identifier or free text)_"
                n_txt = "—"
            elif n == 0:
                vals = "_(empty)_"
                n_txt = "0"
            else:
                vals = "; ".join(f"`{v}` ×{k:,}" for v, k in info["top"])
                if n > len(info["top"]):
                    vals += f"; … (+{n - len(info['top'])})"
                n_txt = f"{n:,}"
            L.append(f"| `{c}` | {n_txt} | {vals} |")

    return "\n".join(L).rstrip("\n") + "\n"


def main(argv: list[str]) -> int:
    root = pathlib.Path(__file__).resolve().parent.parent
    data = (
        pathlib.Path(argv[0]).expanduser()
        if argv
        else pathlib.Path.home() / "Documents/srag-data"
    )
    out = (
        pathlib.Path(argv[1])
        if len(argv) > 1
        else root / "modules/00-dataset/PROFILE.md"
    )

    by_year = profile(data)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(by_year), encoding="utf-8")
    # Trailing newline emitted here, not left to end-of-file-fixer: otherwise the
    # hook adds it, the next run strips it, and the artefact never settles.
    out.with_suffix(".json").write_text(
        json.dumps(by_year, ensure_ascii=False, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(f"{out}")
    print(f"{out.with_suffix('.json')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
